services:
  db:
    image: bitnami/postgresql:latest
    container_name: postgresql
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - my_network
    volumes:
      - postgres_data:/bitnami/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRESQL_USER}"]
      interval: 6s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: fastapi_app
    restart: always
    depends_on:
      - db
    networks:
      - my_network
    ports:
      - "8000:8000"
    env_file:
      - .env

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: streamlit_app
    restart: always
    depends_on:
      - api
    networks:
      - my_network
    ports:
      - "8501:8501"

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data: